import { useEffect, useState } from "react";
import api from "../services/api";
import MainLayout from "../layouts/MainLayout";
import { useAuth } from "../context/AuthContext";
import "./Reports.css";

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Bar } from "react-chartjs-2";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

ChartJS.register(CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend);

function Reports() {
  const [reports, setReports] = useState([]);

  const { user } = useAuth();
  const canGenerate = user?.role === 'Administrator';

  const fetchReports = () => {
    api.get("/energyreports")
      .then((res) => setReports(res.data))
      .catch((err) => console.error(err));
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const generateReport = async () => {
    try {
      await api.post("/energyreports/generate");
      await fetchReports();
      alert("Report Generated Successfully");
    } catch (error) {
      console.error(error);
      alert(error.response?.data?.error || "Failed to Generate Report");
    }
  };

  // ── Chart data ──
  const labels = reports.map((r) =>
    new Date(r.report_month).toLocaleDateString("en-US", {
      month: "short", year: "numeric",
    })
  );
  const savingsData = reports.map((r) => Number(r.savings_percentage));

  // ── Stats ──
  const totalReports  = reports.length;
  const avgSavings    = totalReports ? (savingsData.reduce((a, b) => a + b, 0) / totalReports).toFixed(1) : 0;
  const highestSaving = savingsData.length ? Math.max(...savingsData) : 0;
  const lowestSaving  = savingsData.length ? Math.min(...savingsData) : 0;

  const chartData = {
    labels,
    datasets: [{ label: "Savings %", data: savingsData, backgroundColor: "rgba(37,99,235,0.7)" }],
  };

  // ── Exports ──
  const exportCSV = () => {
    let csv = "Month,Before Consumption,After Consumption,Savings %,Generated By\n";
    reports.forEach((r) => {
      csv += `${r.report_month},${r.before_consumption},${r.after_consumption},${r.savings_percentage},${r.generated_by_name || r.generated_by}\n`;
    });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
    link.download = "energy_reports.csv";
    link.click();
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    doc.text("Smart Street Lighting Reports", 14, 15);
    autoTable(doc, {
      startY: 25,
      head: [["Month", "Before", "After", "Savings %", "Generated By"]],
      body: reports.map((r) => [
        new Date(r.report_month).toLocaleDateString(),
        r.before_consumption,
        r.after_consumption,
        r.savings_percentage,
        r.generated_by_name || r.generated_by,
      ]),
    });
    doc.save("energy_reports.pdf");
  };

  return (
    <MainLayout>
      {/* Page Header */}
      <div className="rp-page-header">
        <h1>Reports</h1>
        <p>Historical energy savings analysis</p>
      </div>

      {/* Stat Cards */}
      <div className="rp-stats-grid">
        <div className="rp-stat-card">
          <h4>Total Reports</h4>
          <h2>{totalReports}</h2>
        </div>
        <div className="rp-stat-card">
          <h4>Average Savings</h4>
          <h2>{avgSavings}%</h2>
        </div>
        <div className="rp-stat-card">
          <h4>Highest Saving</h4>
          <h2>{highestSaving}%</h2>
        </div>
        <div className="rp-stat-card">
          <h4>Lowest Saving</h4>
          <h2>{lowestSaving}%</h2>
        </div>
      </div>

      {/* Buttons */}
      <div className="rp-btn-row">
        {canGenerate && (
          <button onClick={generateReport} className="rp-btn rp-btn-generate">
            Generate Report
          </button>
        )}
        <button onClick={exportCSV} className="rp-btn rp-btn-csv">
          Export CSV
        </button>
        <button onClick={exportPDF} className="rp-btn rp-btn-pdf">
          Export PDF
        </button>
      </div>

      {/* Chart */}
      <div className="rp-chart-card">
        <h3>Monthly Savings Percentage</h3>
        <Bar data={chartData} />
      </div>

      {/* Table */}
      <div className="rp-table-card">
        <h3>Generated Reports</h3>
        <table className="rp-table">
          <thead>
            <tr>
              <th>Month</th>
              <th>Before (kWh)</th>
              <th>After (kWh)</th>
              <th>Savings %</th>
              <th>Generated By</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.report_id}>
                <td>
                  {new Date(report.report_month).toLocaleDateString("en-US", {
                    month: "short",
                    year: "numeric",
                  })}
                </td>
                <td>{Number(report.before_consumption).toLocaleString()}</td>
                <td>{Number(report.after_consumption).toLocaleString()}</td>
                <td>
                  <span className="rp-savings-badge">
                    {Number(report.savings_percentage).toFixed(2)}%
                  </span>
                </td>
                <td>{report.generated_by_name || report.generated_by}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </MainLayout>
  );
}

export default Reports;